### ISSUE TITLE
Bug Script=Unknown

### ISSUE THREAD

**Issue by hjiayz** [eslint-community/regexpp#57]
```
var regexpp = require("@eslint-community/regexpp")
var x = new regexpp.parseRegExpLiteral(/[\p{Script=Unknown}]/u)
```
output:
```
RegExpSyntaxError: Invalid regular expression: /[\p{Script=Unknown}]/u: Invalid property name
```
another 
Script_Extensions=Unknown

**Comment by ota-meshi** [comment]
Thanks for the report.

Looking at the following table, I believe Script=Unknown is an invalid property in ES2022.
https://tc39.es/ecma262/2022/multipage/text-processing.html#table-unicode-script-values

However, ESNext seems to have removed the table of script values.
https://github.com/tc39/ecma262/pull/2649

I think we need to follow that specification change from ES2023.
