### ISSUE TITLE
Support for `v` flag and properties of strings

### ISSUE THREAD

**Issue by RunDevelopment** [eslint-community/regexpp#80]
I wanted to ask whether there are plans to support [the `v` flag and properties of strings](https://github.com/tc39/proposal-regexp-v-flag). The proposal is at stage 3 and [has landed in v8 June 2022](https://v8.dev/features/regexp-v-flag). 

Given the extent of the changes in the proposal, implementing the `v` flag will likely require a new major version for regexpp, because the AST interface will change significantly.

**Comment by ota-meshi** [comment]
I would like to support the v flag.
However, I don't know the best practices for implementing parsers, so I'm not sure if I can implement it well.
I've opened an experimental implementation of the v flag as a draft PR. If you are interested in it, please refer to it. If you can do a better implementation, please open a new PR.

**Comment by ota-meshi** [comment]
It has now reached stage 4.
